project:
  type: website
  output-dir: docs
  
website:
  navbar:
    background: primary
    search: true
    left:
      - text: "Inicio"
        file: index.html
      - text: Unidad 1.html
        file: U01.html
      - text: "About"
        file: about.qmd