project:
  type: website
  output-dir: docs
  
website:
  navbar:
    background: primary
    search: true
    left:
      - text: "Inicio"
        file: index.html
      - talks.qmd
      - text: "About"
        file: about.qmd