---
title: "Unidad 1"
format: html
editor: visual
---

## Introducción a la Ingeniería de Control {#quarto}

### Definiciones {#running-code}

**Variable controlada.** Cantidad o condición que se mide y controla, básicamente es la salida del sistema.

**Señal de control.** También llamada *variable manipulada*. Es la cantidad o condición que el controlador modifica para afectar el valor de la variable controlada.

**Controlar.** Significa medir el valor de la variable controlada del sistema y aplicar la variable manipulada al sistema para corregir o limitar la desviación del valor medido respecto del valor deseado.

**Plantas.** Objeto físico o fenómeno que se va a controlar.

**Procesos.** Operación o desarrollo natural o artificial progresivamente continuo. Es la operación que se va a controlar.

**Sistemas.** Combinación de componentes que actúan juntos con un objetivo predeterminado.

**Perturbaciones.** Señal que tiende a afectar negativamente el valor de la salida de un sistema. Puede ser interna o externa, siendo una entrada más en el primer caso.

**Control realimentado.** Operación que con perturbaciones tiende a reducir la diferencia entre la salida del sistema y alguna entrada de referencia y lo realiza siempre tomando en cuenta esta diferencia. Se aplica a perturbaciones impredecibles ya que las conocidas siempre pueden compensarse.
